### ISSUE TITLE
有偿购买预览版本

### ISSUE THREAD

**Issue by ancientry** [rantianhua/TravelManagement#3]
有偿购买预览版本，不过这个版本无法登陆和注册，有完整预览版本吗？？？qq：1274135463

**Comment by ancientry** [comment]
有偿购买预览版本，不过这个版本无法登陆和注册，有完整预览版本吗？？？qq：1274135463

**Comment by rantianhua** [comment]
那得需要重新编译一下

**Comment by ancientry** [comment]
您这个是完整版本

**Comment by ancientry** [comment]
方便加您qq吗

**Comment by ancientry** [comment]
已经star

**Comment by ancientry** [comment]
编译资料不全，报错

**Comment by ancientry** [comment]
客户需要这个单机小系统：
1：完成预览版我发客户确认；
2：确认后我有偿购买完整的版本；
3：自己开发价格不划算，刚好看到您这个；
4：总上您看可以吗？？？
加您qq：我的qq：1274135463

**Comment by rantianhua** [comment]
不好意思，这个不卖，且是很简陋的东西，没有必要买。

**Comment by ancientry** [comment]
这个有完整版本的您可以发我一份吗？下载编译的文件不全
